name: ${{values.app_name}}-cicd
on:
  push:
    branches:
      - main
    paths:
      - src/**
  pull_request:
    branches:
      - main
    paths:
      - src/**
  workflow_dispatch:

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ '${{ secrets.DOCKERHUB_USERNAME }}' }}
          password: ${{ '${{ secrets.DOCKERHUB_TOKEN }}' }}
      -
        name: Shorten github commit_id
        shell: bash
        run: |
          echo "COMMIT_ID=${GITHUB_SHA::6}" >> ${GITHUB_ENV}
      -
        name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: aumthakkar/${{values.app_name}}-${{values.app_env}}:${{ '${{ env.COMMIT_ID }}' }}
    
    outputs:
        commit_id: ${{ '${{ env.COMMIT_ID }}' }}   
        
  cd:
    needs: ci
    runs-on: self-hosted
    steps:
      - 
        name: Clone your github repo
        uses: actions/checkout@v3        

      - 
        name: Update the values file from Helm chart to have the right tag
        shell: bash
        run: |
          echo ${{ '${{ needs.ci.outputs.commit_id }}' }}
          pip install yq
          yq -Yi '.image.tag = "${{'${{needs.ci.outputs.commit_id}}' }}"' charts/${{values.app_name}}/values-${{values.app_env}}.yaml

      - 
        name: Commit the change
        uses: EndBug/add-and-commit@v9
        with:
          message: "Updates charts/${{values.app_name}}/${{values.app_env}} with latest docker image push commit ${{ '${{needs.ci.outputs.commit_id}}' }}"

      - 
        name: Install ArgoCD application on the runner
        shell: bash
        run: |
          curl -ksSL -o argocd https://github.com/argoproj/argo-cd/releases/latest/download/argocd-linux-amd64
          chmod +x argocd
          sudo mv ./argocd /usr/local/bin/argocd

      - 
        name: Login to ArgoCD and Create the app
        shell: bash
        run: |
          argocd login argocd-server.argocd \
          --insecure \
          --grpc-web \
          --username admin \
          --password ${{ '${{ secrets.ARGOCD_PASSWORD }}' }}
        
      - name: ArgoCD App create
        shell: bash
        run: |
          # Connect the argocd repo.
          repo="https://github.com/aum-thakkar/${{values.app_name}}.git"
          argocd repo list | grep -q ${repo} || argocd repo add ${repo}

          # Delete argocd app first if exists to start afresh.
          if argocd app get ${{ values.app_name }} >/dev/null 2>&1; then
                        echo "Deleting old re-iteration of ${{ values.app_name }} app first to start afresh."
                        argocd app delete ${{ values.app_name }} --cascade --yes --wait

                        while argocd app get ${{ values.app_name }} >/dev/null 2>&1; do
                            echo "Waiting for argocd app: '${{ values.app_name }}' to be deleted..."
                            sleep 2
                        done
                    fi
          
          # Create argocd app.
          argocd app create ${{values.app_name}} \
          --dest-namespace ${{values.app_env}} \
          --dest-server https://kubernetes.default.svc \
          --revision main \
          --sync-option CreateNamespace=true \
          --sync-policy manual \
          --repo ${repo} \
          --path charts/${{values.app_name}} \
          --values values-${{values.app_env}}.yaml
      
      - name: ArgoCD app sync
        shell: bash
        run: | 
          argocd app sync ${{values.app_name}}
          argocd app wait ${{values.app_name}} --timeout 120

      
    
